### ISSUE TITLE
Custom colors for offpath, vertical/horizontal

### ISSUE THREAD

**Issue by 75th** [Mark2Mark/show-stems-pro-plugin#7]
The [project page](https://markfromberg.com/projects/stems/) says that off-path badges can be any customizable color, but I can't find any documentation on how to change it. I assume it's a custom parameter, but Glyphs doesn't suggest it (can plugins even add suggestions to that list?) and I don't feel like guessing. :)

Further, it would help me if I could make vertical badges one color and horizontal badges another. If there's a parameter for that I'd love to know it, and if there's not I'd love for there to be one.

**Comment by Mark2Mark** [comment]
Hi @75th 

This Project Page is for the Glyphs 2 Version of Show Stems and the 'any' color is changed in the Glyphs 3 Version (whcih this repository is about) to the Mac OS System Accent color. I dropped the support for the 'any' custom color due to too little request (actually it was ever just asked for by one user) and too much of additional maintainance effort. Both were not in a healthy balance.

You can now easily change the color by changing your accent color of the Mac in the System Preferences. Is that not enough of a choice? If not, what color(s) do you need?

Also thanks for the idea about different colors for vertical an horizontal. I made the direction icons on purpose for easier distinction. I think even more colors could add to confusion. Which colors would you set up if that would be possible?

**Comment by Mark2Mark** [comment]
closing issue due to missing response. Feel free to re-open.
